name: Terraform Apply
on:
  push:
    branches:
      - master
    paths:
      - '**.tf'
env:
  AWS_IAM_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-Pan-For-Gold
  AWS_REGION: us-east-1
  BUCKET_NAME: pan-for-gold-tf-backend-${{ secrets.AWS_ACCOUNT_ID }}
  BUCKET_REGION: us-east-1
  CLUSTER_NAME: pan-for-gold
  DYNAMODB_NAME: GitHubActions-Pan-For-Gold-Terraform-Lock
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          role-session-name: GitHubActionsTerraformSession
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform
        id: init
        run: >
          terraform init -no-color
          -backend-config bucket=${{ env.BUCKET_NAME }}
          -backend-config key=${{ env.CLUSTER_NAME }}/${{ env.CLUSTER_NAME }}.tfstate
          -backend-config region=${{ env.BUCKET_REGION }}
          -backend-config dynamodb_table=${{ env.DYNAMODB_NAME }}

      - name: Terraform Apply
        working-directory: terraform
        id: apply
        run: >
          terraform apply -no-color -compact-warnings -auto-approve
          -var region=${{ env.AWS_REGION }}
          -var name=${{ env.CLUSTER_NAME }}
